# Generated by Django 5.0.9 on 2024-11-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
